name: Update Clash Config

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at 00:00 UTC
  workflow_dispatch:     # Manual trigger

jobs:
  update-clash-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest ACL4SSR_Online_Full.yaml
        run: |
          # 确保目标目录存在
          mkdir -p ./clash || true          # -p 不报错， || true 防止错误终止
          echo "Trying to download file..."
          
          # 使用 curl -L 跟随重定向
          if ! curl -L -o ./clash/ACL4SSR_Online_Full.yaml \
            "https://raw.githubusercontent.com/mihomo-party-org/override-hub/main/yaml/ACL4SSR_Online_Full.yaml"; then
            echo "❌ Failed to download file!"
            exit 1  # 如果下载失败，直接终止 workflow
          else
            echo "✅ File downloaded successfully!"
          fi
          curl -L -o ./clash/CF优选官方IP(无交互三地区电脑版).zip https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/refs/heads/main/CF%E4%BC%98%E9%80%89%E5%AE%98%E6%96%B9IP(%E6%97%A0%E4%BA%A4%E4%BA%92%E4%B8%89%E5%9C%B0%E5%8C%BA%E7%94%B5%E8%84%91%E7%89%88).zip
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./clash/ACL4SSR_Online_Full.yaml
          
          # - 检查是否更改
          if git diff --cached --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git commit -m "chore: update Clash config from upstream [$(date +'%Y-%m-%d %H:%M UTC')]"
            git push
          fi
